// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awziphxdaeswhjrjgbui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3emlwaHhkYWVzd2hqcmpnYnVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MjE2ODMsImV4cCI6MjA3MTk5NzY4M30.CqkWFlzCxp02tJCNas5qvij8Cv2embVpqQie1WvvGNY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});